name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: composer test

  publish:
    name: Publish to Packagist
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Notify Packagist
        run: |
          curl -XPOST \
            -H "Authorization: token ${{ secrets.PACKAGIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/didanurwanda/inflector-php"}}' \
            https://packagist.org/api/update-package
